// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJb5I9CBBjQKgijuOJ3qT4pB1BcvUvxxA',
    appId: '1:625241073475:web:4fd1f276767828a42cb1f6',
    messagingSenderId: '625241073475',
    projectId: 'bpjs-inventory',
    authDomain: 'bpjs-inventory.firebaseapp.com',
    storageBucket: 'bpjs-inventory.appspot.com',
    measurementId: 'G-CDTRS58QBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjc0P0I8J50QSPJ12edW0qUHnkLFp4kU',
    appId: '1:625241073475:android:1a5afbd98eeda41e2cb1f6',
    messagingSenderId: '625241073475',
    projectId: 'bpjs-inventory',
    storageBucket: 'bpjs-inventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQehcBbT9jKiMh4M5C_aNgJY4cEa_3bc',
    appId: '1:625241073475:ios:136b4f1cb5849c222cb1f6',
    messagingSenderId: '625241073475',
    projectId: 'bpjs-inventory',
    storageBucket: 'bpjs-inventory.appspot.com',
    iosBundleId: 'com.example.bpjsInventory',
  );
}
